/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#e6eeff",
        "inverse-primary": "#b2c5ff",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffdbc8",
        "primary-fixed-dim": "#b2c5ff",
        "secondary-container": "#fb7800",
        "surface-container-highest": "#d5e3fc",
        "on-error-container": "#93000a",
        "on-secondary-container": "#592600",
        "on-secondary-fixed": "#321200",
        "on-tertiary-container": "#ffcebd",
        "tertiary": "#822800",
        "primary-fixed": "#dae2ff",
        "primary-container": "#0056d2",
        "background": "#f8f9ff",
        "tertiary-fixed": "#ffdbcf",
        "surface-tint": "#0056d2",
        "on-primary-container": "#ccd8ff",
        "surface-container-high": "#dce9ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#994700",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "on-surface": "#0d1c2e",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#ffb68b",
        "outline-variant": "#c3c6d6",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "on-primary-fixed": "#001847",
        "on-background": "#0d1c2e",
        "tertiary-fixed-dim": "#ffb59b",
        "primary": "#0040a1",
        "inverse-surface": "#233144",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424654",
        "on-primary": "#ffffff",
        "tertiary-container": "#a93802",
        "outline": "#737785",
        "on-primary-fixed-variant": "#0040a1",
        "on-tertiary-fixed-variant": "#812800",
        "surface-variant": "#d5e3fc",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#753400",
        "on-error": "#ffffff",
        "surface-dim": "#ccdbf3"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}